### ISSUE TITLE
Create a tutorial with an example on how to use the downloaded ressources for other kinds of analysis and mapping

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#159]
Background:
Our packages providers a downloader function for a specific AOI from several different sources and stores it locally. Our processing routines however only focus on aggregating these indicators in the AOI. Other analysis such as point pattern are not possible but very interesting for a more general public. Also using the raw data to create maps and better understand the spatial distribution below an aggregated statistic might have a high value. 

Suggestion: 
Create a vignette that shows where data is stored, how it could be used e.g. to create a raster from it showing like  a heatmap and plot the data in an interactive map. 

Example: 
Download point data for an AOI -> create a raster heat map -> plot AOI, heatmap and point data with `mapView`

**Comment by goergen95** [comment]
I have set up a first draft for such a vignette. If you want to build the website locally run:

```bash
git pull origin
git checkout 159-tutorial
```
Then if you start R run `pkgdown::build_site()`. You might need to install some dependencies for this to be successful. Looking forward to your feedback!

**Comment by karpfen** [comment]
I had a look at the vignette; Very cool! I think this kind of walk-through is really useful for practitioners. I also liked the EDA at the end to give an idea of what's possible with the data.
I have one point I'd like to address, though: I think the name "Access" is a bit nondescript. Maybe something along the lines of "Practical example: data download and analysis" or some other, more speaking, name would make the purpose of the vignette much clearer. What do you think?

**Comment by goergen95** [comment]
Great! Thanks for having a look! I totally agree about the name!! The problem was that in the articles tab of the navbar all other sites have a single name so I was looking for something that would fit that approach. You got any better idea than "access" or maybe just something with 2 words? :D

**Comment by karpfen** [comment]
Yeah, that makes sense. Maybe one of:
- Hands-on example
- Walk-through
- Practical example
- Example: NASA FIRMS
- Full example

or some combination thereof?

**Comment by goergen95** [comment]
How about a new component in the navbar dedicated for examples?

```yaml
   articles:
     text: Articles
     menu:
       - text: Introduction
         href: articles/introduction.html
       - text: Installation
         href: articles/installation.html
       - text: Terminology
         href: articles/terminology.html
       - text: Workflow
         href: articles/workflow.html
       - text: Contributing
         href: articles/contributing.html
   examples:
     text: Examples
     menu:
       - text: NASA FIRMS
         href: articles/nasa-firms.html
```
